# Generated by Django 3.2.4 on 2021-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name_test',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
